"""initial schema

Revision ID: c48596981732
Revises: 
Create Date: 2026-07-22 22:38:17.974441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c48596981732'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criminals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('ksp_criminal_id', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('alias', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('religion', sa.String(length=100), nullable=True),
    sa.Column('present_address', sa.Text(), nullable=True),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('identifying_marks', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('is_repeat_offender', sa.Boolean(), nullable=False),
    sa.Column('is_wanted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_number'),
    sa.UniqueConstraint('ksp_criminal_id')
    )
    op.create_table('stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('taluk', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('jurisdiction_area_sqkm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('officers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('badge_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('rank', sa.Enum('constable', 'head_constable', 'asi', 'si', 'psi', 'pi', 'dysp', 'sp', 'dig', 'ig', 'dgp', name='officerrank'), nullable=False),
    sa.Column('role', sa.Enum('officer', 'supervisor', 'analyst', 'admin', name='officerrole'), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('jurisdiction_district', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_number'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=200), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('request_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('firs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fir_number', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('investigating_officer_id', sa.UUID(), nullable=True),
    sa.Column('crime_category', sa.Enum('murder', 'attempt_to_murder', 'kidnapping', 'robbery', 'dacoity', 'theft', 'burglary', 'cheating', 'fraud', 'cyber_crime', 'drug_offence', 'assault', 'sexual_assault', 'domestic_violence', 'motor_vehicle_theft', 'extortion', 'arson', 'forgery', 'other', name='crimecategory'), nullable=False),
    sa.Column('sections_applied', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('registered', 'under_investigation', 'chargesheeted', 'closed', 'transferred', 'final_report', name='firstatus'), nullable=False),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('incident_location', sa.String(length=500), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('complainant_name', sa.String(length=200), nullable=True),
    sa.Column('complainant_phone', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_organized_crime', sa.Boolean(), nullable=False),
    sa.Column('is_inter_district', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigating_officer_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fir_number')
    )
    op.create_table('criminal_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fir_id', sa.UUID(), nullable=False),
    sa.Column('criminal_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('main_accused', 'co_accused', 'abettor', 'suspect', 'witness', 'informant', name='accusedrole'), nullable=False),
    sa.Column('arrest_status', sa.Enum('not_arrested', 'arrested', 'absconding', 'bailed', 'convicted', 'acquitted', name='arreststatus'), nullable=False),
    sa.Column('arrest_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_notes', sa.Text(), nullable=True),
    sa.Column('known_associates_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['fir_id'], ['firs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('criminal_links')
    op.drop_table('firs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('officers')
    op.drop_table('stations')
    op.drop_table('criminals')
    # ### end Alembic commands ###
